# Generated by Django 5.0.6 on 2024-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_alter_movie_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='moviedb.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
