# Generated by Django 5.0.6 on 2024-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0008_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
