# Generated by Django 5.0.6 on 2024-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0009_series_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='summary',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
