# Generated by Django 5.0.6 on 2024-07-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_genre_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
