# Generated by Django 5.0.6 on 2024-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0005_movie_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
