# Generated by Django 5.0.6 on 2024-07-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0011_remove_series_imdb_id_alter_genre_id_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
