# Generated by Django 5.0.6 on 2024-08-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0016_series_genres_series_overview_series_poster_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='number',
            new_name='episode_number',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='number',
            new_name='season_number',
        ),
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='vote_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='episode_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='series',
            name='number_of_episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='number_of_seasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
