# Generated by Django 5.0.6 on 2024-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0017_rename_number_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
